About Me
Experience
theme: jekyll-theme-minimal


Education
University of Massachusetts, Boston
B.S. Computer Science, GPA 3.88
Professional Experiences
Subject Matter Expert / Online Instructor
Coursera, Mountain View, CA
March 2020 - Present

    Create interactive online IT courses
    Teach students worldwide

